'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null,users=[],sessions=[],active=null,draftTimer=null,dirty=false;
async function api(path,data){let r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},credentials:'same-origin',body:data===undefined?undefined:JSON.stringify(data)});let j=await r.json();if(!r.ok)throw Error(j.error||'Error de conexión');return j}
const date=s=>new Date(s).toLocaleString('es-AR'), month=s=>{let d=new Date(s);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')};
function duration(s){let seconds=Math.max(0,Math.round((new Date(s.ended)-new Date(s.started))/1000));return seconds}
function time(seconds){let min=Math.round(seconds/60);return Math.floor(min/60)+' h '+String(min%60).padStart(2,'0')+' min'}
function download(rows,name){let csv=rows.map(row=>row.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(';')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function refresh(){sessions=(await api('sessions')).sessions;active=sessions.find(s=>s.user_id===me.id&&!s.ended)||null;renderWork();renderHistory();if(me.role==='admin'){users=(await api('users')).users;renderUsers();renderHours()}}
function renderWork(){let on=!!active;$('startBtn').disabled=on;$('finishBtn').disabled=!on;$('editor').hidden=!on;$('sessionState').textContent=on?'Sesión iniciada: '+date(active.started):'No hay una sesión activa.';if(on){$('resumen').value=active.resumen;$('acta').value=active.acta}else{$('resumen').value='';$('acta').value=''}tick()}
function tick(){if(!active){$('timer').textContent='00:00:00';return}let sec=Math.max(0,Math.floor((Date.now()-new Date(active.started))/1000));$('timer').textContent=[Math.floor(sec/3600),Math.floor(sec%3600/60),sec%60].map(n=>String(n).padStart(2,'0')).join(':')}
setInterval(tick,1000);
async function saveDraft(){if(!active||!dirty)return;let data={resumen:$('resumen').value,acta:$('acta').value};try{await api('draft',data);active.resumen=data.resumen;active.acta=data.acta;dirty=false;$('saved').textContent='Guardado en el servidor: '+new Date().toLocaleTimeString('es-AR')}catch(e){$('saved').textContent='No se pudo guardar: '+e.message; $('saved').className='error'}}
function changed(){dirty=true;$('saved').textContent='Guardando…';clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,700)}
$('resumen').addEventListener('input',changed);$('acta').addEventListener('input',changed);
$('startBtn').onclick=async()=>{try{await api('start',{});await refresh();$('workMsg').textContent='Virtualidad iniciada.'}catch(e){alert(e.message)}};
$('finishBtn').onclick=async()=>{if(!active)return;if(!confirm('¿Finalizar esta sesión? El acta quedará guardada.'))return;clearTimeout(draftTimer);try{let result=await api('finish',{resumen:$('resumen').value,acta:$('acta').value});dirty=false;await refresh();$('workMsg').textContent='Sesión finalizada. '+result.notice}catch(e){alert(e.message)}};
function renderHistory(){let visible=me.role==='admin'?sessions:sessions.filter(s=>s.user_id===me.id);$('historyTable').innerHTML=visible.length?`<table><tr><th>Profesional</th><th>Área / Equipo</th><th>Inicio</th><th>Fin</th><th>Duración</th><th>Resumen</th><th>Acta</th></tr>${visible.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.area)} / ${esc(s.equipo)}</td><td>${date(s.started)}</td><td>${s.ended?date(s.ended):'Activa'}</td><td>${s.ended?time(duration(s)):'En curso'}</td><td>${esc(s.resumen).slice(0,160)}${s.resumen.length>160?'…':''}</td><td><button class="btn primary" data-acta="${s.id}">Ver acta</button></td></tr>`).join('')}</table>`:'No hay registros.';$('historyTable').querySelectorAll('[data-acta]').forEach(b=>b.onclick=()=>{let s=sessions.find(x=>x.id===Number(b.dataset.acta));$('actaTitle').textContent='Acta · '+s.name+' · '+date(s.started);$('actaTexto').textContent=s.acta||'Sin acta cargada.';$('actaDialog').showModal()})}
$('closeActa').onclick=()=>$('actaDialog').close();
$('exportSessions').onclick=()=>download([['Profesional','Área','Equipo','Inicio','Fin','Minutos','Resumen','Acta'],...sessions.filter(s=>me.role==='admin'||s.user_id===me.id).map(s=>[s.name,s.area,s.equipo,date(s.started),s.ended?date(s.ended):'',s.ended?Math.round(duration(s)/60):'',s.resumen,s.acta])],'SAIE_registros.csv');
function hourRows(){let from=$('fromMonth').value,to=$('toMonth').value,filter=$('filterUser').value;if(from&&to&&from>to)return null;let rows=new Map(users.filter(u=>u.role==='professional'&&(!filter||String(u.id)===filter)).map(u=>[u.id,{name:u.name,area:u.area,equipo:u.equipo,count:0,seconds:0}]));for(let s of sessions){if(!s.ended||from&&month(s.started)<from||to&&month(s.started)>to||filter&&String(s.user_id)!==filter)continue;let row=rows.get(s.user_id);if(!row){row={name:s.name,area:s.area,equipo:s.equipo,count:0,seconds:0};rows.set(s.user_id,row)}row.count++;row.seconds+=duration(s)}return [...rows.values()].sort((a,b)=>a.name.localeCompare(b.name,'es'))}
function renderHours(){let previous=$('filterUser').value;$('filterUser').innerHTML='<option value="">Todos</option>'+users.filter(u=>u.role==='professional').map(u=>`<option value="${u.id}">${esc(u.name)} — ${esc(u.area)}</option>`).join('');$('filterUser').value=previous;let rows=hourRows();if(!rows){$('hoursTable').textContent='El mes inicial no puede ser posterior al final.';return}let total=rows.reduce((n,r)=>n+r.seconds,0),count=rows.reduce((n,r)=>n+r.count,0);$('hoursTable').innerHTML=`<p><b>Total: ${time(total)}</b> · ${count} sesiones finalizadas</p><table><tr><th>Profesional</th><th>Área</th><th>Equipo</th><th>Sesiones</th><th>Horas trabajadas</th></tr>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.area)}</td><td>${esc(r.equipo)}</td><td>${r.count}</td><td>${time(r.seconds)}</td></tr>`).join('')}</table>`}
['fromMonth','toMonth','filterUser'].forEach(id=>$(id).addEventListener('change',renderHours));
$('exportHours').onclick=()=>{let rows=hourRows();if(!rows)return alert('Revisá el rango de meses');download([['Profesional','Área','Equipo','Sesiones','Minutos'],...rows.map(r=>[r.name,r.area,r.equipo,r.count,Math.round(r.seconds/60)])],'SAIE_horas.csv')};
function renderUsers(){$('usersTable').innerHTML=`<table><tr><th>Nombre</th><th>Usuario</th><th>Área</th><th>Equipo</th><th>Correo de coordinación</th></tr>${users.filter(u=>u.role==='professional').map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${esc(u.area)}</td><td>${esc(u.equipo)}</td><td>${esc(u.recipient)}</td></tr>`).join('')}</table>`}
$('addUser').onclick=async()=>{let data={name:$('name').value,username:$('username').value,password:$('newPass').value,area:$('area').value,equipo:$('equipo').value,email:$('email').value,recipient:$('recipient').value};try{await api('users',data);['name','username','newPass','email','recipient'].forEach(id=>$(id).value='');$('userMsg').textContent='Profesional agregado.';await refresh()}catch(e){$('userMsg').textContent=e.message}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab!=='work')refresh().catch(console.error)});
$('loginBtn').onclick=async()=>{try{await api('login',{username:$('loginUser').value,password:$('loginPass').value});$('loginPass').value='';await boot()}catch(e){$('loginMsg').textContent=e.message}};
$('logoutBtn').onclick=async()=>{if(dirty)await saveDraft();await api('logout',{});location.reload()};
async function boot(){try{me=(await api('me')).user;$('login').hidden=true;$('app').hidden=false;$('identity').textContent=me.name+' · '+(me.role==='admin'?'Administración':me.area+' · '+me.equipo);document.querySelectorAll('.admin-only').forEach(x=>x.hidden=me.role!=='admin');let current=new Date(),ym=current.getFullYear()+'-'+String(current.getMonth()+1).padStart(2,'0');$('fromMonth').value=$('toMonth').value=ym;await refresh()}catch(e){$('login').hidden=false;$('app').hidden=true}}
boot();
